@ArchiSyncServer.Api_HostAddress = https://localhost:7218

GET {{ArchiSyncServer.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@projectId=0
GET {{ArchiSyncServer.Api_HostAddress}}/api/projectpermission/{{projectId}}/check-permission

###

POST {{ArchiSyncServer.Api_HostAddress}}/api/sketch/convert
Content-Type: application/json

{
  //SketchRequest
}

###

POST {{ArchiSyncServer.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  //RegisterModel
}

###
